[package]
name = "quadranet"
version = "0.2.0"
edition = "2021"

[dependencies]
lora-phy = { git = "https://github.com/lora-rs/lora-rs", version = "3.0" }
embedded-hal-async = "1.0.0"
snafu = { version = "0.8", default-features = false }
heapless = "0.8"
postcard = "1.0"
defmt = "0.3"
defmt-rtt = "0.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dependencies.embassy-time]
version = "0.3.2"
git = "https://github.com/embassy-rs/embassy"
features = ["defmt", "defmt-timestamp-uptime"]

[dev-dependencies]
postcard = { version = "1.0", features = ["alloc"] }

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true
