[package]
name = "quadranet"
version = "0.1.0"
edition = "2021"

[dependencies]
lora-phy = "2.1"
embassy-time = "0.1"
embedded-hal-async = "1.0.0-rc.1"
snafu = { version = "0.7.5", default-features = false }
heapless = "0.7"
