[package]
name = "quadranet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lora-phy = "2.1"
embassy-time = "0.1.1"
embedded-hal-async = "0.2.0-alpha.2"
snafu = { version = "0.7.5", default-features = false }